{
 "title": "TestDashboard1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "controllers",
    "label": "controllers",
    "query": {
     "query": "label_values(http_requests_received_total, controller)"
    }
   },
   {
    "name": "razorpageroutes",
    "label": "razorpages",
    "query": {
     "query": "label_values(razor_page_requests_total, route)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error rate of each API controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (rate(http_requests_received_total{controller =~ \"$controllers\", code=~\"5\\\\d\\\\d|4\\\\d\\\\d\"}[1m])) by(controller)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Amount of page visits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(razor_page_requests_total{route=~\"$razorpageroutes\"}[1m])) by(route)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received http requests of each API controller",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(controller) (rate(http_requests_received_total{controller=~\"$controllers\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}